name: Nextjs CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-v3-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn
      - name: Linting codebase
        run: yarn lint
      - name: Build Nextjs
        env:
          APP_URL: ${{ secrets.APP_URL }}
        run: yarn build
